services:
  mysql:
    image: mysql:8.0
    container_name: cnab-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword 
      MYSQL_DATABASE: cnab_database
      MYSQL_USER: cnab_user
      MYSQL_PASSWORD: password123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - cnab-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "cnab_user", "-p$$MYSQL_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cnab-backend
    restart: always
    environment:
      DB_HOST: mysql
      DB_USER: cnab_user
      DB_PASSWORD: password123
      DB_NAME: cnab_database
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - cnab-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cnab-frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - cnab-network

volumes:
  mysql_data:

networks:
  cnab-network:
    driver: bridge